### ISSUE TITLE
Pen configuration tab > Crash

### ISSUE THREAD

**Issue by celfred** [OpenBoard-org/OpenBoard#124]
Hello,

First of all thanks a lot for the 1.4.0 version !
I've just installed it on my Ubuntu 16.04 and I've noticed this minor thing : if I go to the preferences panel and click on 'Pen', OpenBoard crashes (it automatically quits).
When launched from the console, it just says 'Erreur de segmentation (core dumped)'.

Hope it helps.

**Comment by SCdipsem** [comment]
Hello,
Thank you for your return, but I can not reproduce your bug on a KUbuntu 16.04. Could you try on another computer?

**Comment by freeheel3r** [comment]
A while ago, I experienced some crashes when opening the Pen tab that were due to configuration file changes from one version to the next. I had fixed it then, but it's possible that a new, similar issue arose.

Could you try deleting (or better yet, moving) your configuration files? There should be one in `~/.local/share/data/OpenBoard/OpenBoardUser.config` and one in `/opt/OpenBoard/etc/OpenBoard.config` .

If you close OpenBoard, then move/rename these files, then open OpenBoard again, does it still crash when switching to the pen tab?
If so, could you post these configuration files?
Thanks!

**Comment by celfred** [comment]
@freeheel3r Spot on ! I've tried moving my config file in .local/share and no more crash.
Just so you know, here's how I work (which maybe is a bad idea) : I make a symbolic link towards my /home/OpenBoard/ so I can keep all my documents, tools, config files somewhere else than .local/share/OpenBoard. And I guess this is the reason for the crash.
I've tried to only symlink my 'document' folder and copy my old OpenBoardUser.config into my .local/share : the crash still happens. If I start with a fresh new OpenBoardUser.config : no more crash.

I guess I'll try to reset all my things from a new OpenBoardUser.config and THEN try to symlink. I have a feeling this will work :) but I'll need more time so it'll be later during the day. I'll keep you updated.

**Comment by celfred** [comment]
So I did more tests very quickly : 
- symbolic links don't matter
- the problem in my old user config comes from the line : PenDarkBackgroundSelectedColors=#FFFFFF, #ff0000, #004080, #008000, #000000 (I hard-coded personal colors)

When I get rid of this line, no more crash on the Pen tab and I can manually click the colors (which writes the same line with different colors in the config file).

**Comment by freeheel3r** [comment]
You should make sure that the "selected colors" all exist in the "colors" line corresponding to it. For your example, make sure that "PenDarkBackgroundSelectedColors" contains these colors you specified.

It's a little silly that OpenBoard crashes for such a small detail though, maybe there's something that could be done about that.

**Comment by celfred** [comment]
Thanks for the answer, but I had trouble to understand you ;)
Eventually, I got rid of the crash and managed to use my personal colors by adding : 

> PenDarkBackgroundColors=#FFFFFF, #ff008000, #004080, #ffff0000, #000000
> PenDarkBackgroundSelectedColors=#FFFFFF, #ff008000, #004080, #ffff0000, #000000

(note the 'Selected' out in first line).

From what I've understood from your post, the 1st line should list all possible colors available when we click on colors in the 'Pen' tab.

As you said, OB shoudn't crash because of this, but that's not a big issue either :)
Maybe all colors should be made available by default (so line 1 would become useless) and clicking on a color square in the 'Pen' tab could open a classic complete color selection box with all possible colors one could choose from.

**Comment by kaamui** [comment]
hello,

It's a known issue related to how colors configuration is handled. You can also make OpenBoard crash by clicking on the corresponding tab, when having less than 5 colors defined in the parameters MarkerDarkBackgroundColor or PenLightBackgroundColors for example. 

All of this should be reworked but we don't enough resources, and because it can be easily fixed by cleaning the corresponding parameters on your config file, it's not going to be a priority :)

**Comment by freeheel3r** [comment]
> You can also make OpenBoard crash by clicking on the corresponding tab, when having less than 5 colors defined in the parameters MarkerDarkBackgroundColor or PenLightBackgroundColors for example.

Does that actually still happen? It shouldn't, it's handled specifically in [UBSettings](https://github.com/OpenBoard-org/OpenBoard/blob/master/src/core/UBSettings.cpp#L1412). 

It should be fairly easy to add checks for whatever other settings-related crashes could happen.
