### ISSUE TITLE
drawing on gnome desktop fails

### ISSUE THREAD

**Issue by helge42** [OpenBoard-org/OpenBoard#209]
The drawings on the gnome desktop are not visible (and the red pointer :-( ). After a click on the keyboard-icon of openboard the drawing strokes  appear. The next drawings are only visible near the first ones.

I use version 1.5.1.

**Comment by kaamui** [comment]
Hello,

What is your operating system ?

**Comment by helge42** [comment]
Hi,
it is debain stretch
```
$ cat /etc/issue
Debian GNU/Linux 9 \n \l 
```

**Comment by bartoszek** [comment]
Reproduced on {distro=Arch,gnome=3.32,xorg=1.20.4}

**Comment by kaamui** [comment]
Hello,

A workaround is available on the dev branch (only tested on Ubuntu 18 but could help when using Gnome Desktop).

[commit](https://github.com/OpenBoard-org/OpenBoard/commit/94140cbc4b2f055ca282de006a09d335a49c550e#diff-25d902c24283ab8cfbac54dfa101ad31)

Thank you for reporting it.

**Comment by helge42** [comment]
Thanks, this is great. I will test it on debian, but I can't compile openboard by myself.

@JBBgameich or @sunweaver Is it possible that you make a new flatpack or deb package with the commit? 

... or is there another way for me to test the fix with debian?

**Comment by JBBgameich** [comment]
I could probably publish a flatpak on the beta channel.
You could try building my openboard repo on gitlab (just use the dev branch and merge the upstream dev branch into it before). It should compile on debian without requiring any hacks or third party binaries.

**Comment by JBBgameich** [comment]
I just published a beta build. You can install it using this command:
`flatpak install https://flathub.org/beta-repo/appstream/org.godotengine.Godot.flatpakref`
Afterwards run it using this command `flatpak run ch.openboard.OpenBoard//beta`, to make sure the beta version is actually launched if you have both the stable and the beta installed.

**Comment by kaamui** [comment]
hello guys,

The workaround actually doesn't work at all as it prevents from doing any action with the background, sorry.

Don't spend too much effort on the dev branch as it can easily contain some broken/unstable states. 

I'll keep you up !

**Comment by kaamui** [comment]
Hello,

I reverted the previous workaround. For now, I cannot spend much time on it, but I tried the pull request #67 and it seems to be close to what we want (drawing visible and background actions still possible outside of the drawn area), but there are some issues with the floating palettes. I'll work on it later.

**Comment by helge42** [comment]
@JBBgameich thank you for the beta flatpak. It worked nicely, but kaamui was faster with the posting ;-)

**Comment by helge42** [comment]
Ubuntu 18.04 is based on gnome. So the openboard version for ubuntu (#231) is still not working at all, because the desktop mode isn't working.

Is there a change that this will be fixed? (This is the last showstopper for switching to linux in our school ;-)

**Comment by kaamui** [comment]
Hello,

As you can see, I pinned the issue and added the label "Community help needed", because we know this issue is important, but we cannot currently spend time on it. Some attempts like #67 were close to fix it.  

If it can help you to switch to linux in your school, please note that this is a gnome-related issue. It is working well in KUbuntu (the version we actually use in Geneva schools)

**Comment by jondo** [comment]
The same issue appears on the Cinnamon desktop (seen on Linux Mint 19.2, based on Ubuntu 18.04.2).
(Everything works fine on the Linux Mint 19.2 version with Mate desktop.)

**Comment by CaptainBasculin** [comment]
Same issue on Pop's Gnome DE. I would suggest anyone else needing to use this mode to use with KDE for now.

**Comment by fersdt** [comment]
@kaamui i tried to use OpenBoard with Gnome. Desktop Mode doesn't work. I have read the past messages and issues. Is there no solution to solve the problem with Gnome when using OpenBoard in Desktop Mode ?

**Comment by sunweaver** [comment]
On  Mo 06 Jul 2020 23:42:20 CEST, fersdt wrote:

> @kaamui i tried to use OpenBoard with Gnome. Desktop Mode doesn't  
> work. I have read the past messages and issues. Is there no solution  
> to solve the problem with Gnome when using OpenBoard in Desktop Mode ?

I guess, it would be really helpful, if people mentioned whether they  
use OpenBoard on GOME+Wayland or on GNOME+Xorg...

Latest Ubuntu (18.04 LTS through to 20.04 LTS) runs GNOME on Xorg by default.

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler Str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by fersdt** [comment]
I'm really sorry @sunweaver, I forgot to mention it. I use Gnome +Xorg.
Linux distribution : Debian 10

**Comment by alexispaz** [comment]
Same issue 

```
linux=5.8.5-arch1-1
gnome=3.36.5
Wayland=1.18.0-2
```

**Comment by alexispaz** [comment]
BTW. It also happens if I run gnome on Xorg.

**Comment by alexispaz** [comment]
I just installed the alpha version v1.6.0a3 and now the problem is that I can not even draw, i.e. the mouse interact with the desktop as if openboard does not exist, despite the pen is selected an the toolbar is visible.

**Comment by MuhammedTaha02** [comment]
https://yadi.sk/i/kCKbSTnDLrNqLA

Openboard does not work properly on all gnome based desktops. First of all, I tested it in archlinux gnome (openboard aur package) and fedora gnome (openboard pkgs.org package) respectively. Both of them there was an error on the link above. My last stop was on gentoo (openboard flatpak package). The same error occurred here.

**Comment by fersdt** [comment]
Hi !

 I see this issue is closed, but drawing on gnome desktop is continuing to fail !
 My distro is Debian 10 and I use Gnome with Xorg. Any advance in this issue since 2019 ?
 
 Thanks in advance for your help

**Comment by JBBgameich** [comment]
The issue is still open, so the bug is probably still there.

**Comment by kaamui** [comment]
afaik, the issue is no longer occuring on Uvuntu 20.04 with Openvoard 1.6.1

**Comment by MuhammedTaha02** [comment]
Openboard works fine in Flatpak beta. But in wayland it's problematic again.

**Comment by neurofreak-alt** [comment]
Incorrect display of drawn items on the desktop via OpenBoard on Alt Linux


![not_drawing_on_desktop](https://user-images.githubusercontent.com/69948933/165215249-f377593c-240f-4100-9307-89d8e6859a0d.png)

Package version: OpenBoard-1.6.1

Steps leading to the error:
1) Start OpenBoard.
2) Select "Desktop" from toolbar
3) Choose "annotate document" tool and draw something

Result:
The picture is drawn only in a certain area. If you go back to the board and then back to the desktop, the area is enlarged and anything that was drawn outside the original area is displayed in that enlargement.

Expected result:
You can draw on the entire desktop

Optional:
Observed only on mate desktop environment

Thanx for attention.

**Comment by Stehlampe2020** [comment]
I don't know if it is of real interest, on Ubuntu Unity 22.04 it also has this issue,   
as well as on Linux Mint 21 Cinnamon (Cinnamon 5.something, I believe...) and on Ubuntu Gnome 22.04 LTS. 
(all three with the official \*.deb from openboard.ch, downloaded in late 2022)

**Comment by SpaggetECode** [comment]
This still continues to not work in MANY major Debian base Linux distributions including all flavors of Mint.
