### ISSUE TITLE
Extended screen mode

### ISSUE THREAD

**Issue by vivianecs** [OpenBoard-org/OpenBoard#536]
In extended screen mode (Windows 10) and with Openboard 1.6.1 in the secondary monitor, the Openboard Menu is opened in the primary, main monitor.
![20211029_192854_remastered](https://user-images.githubusercontent.com/57958655/139770278-b4ac6b00-58fd-4b97-b0cd-88e397f9fe36.jpg)

**Comment by FiSHYsolutions** [comment]
i can confirm this pretty annoying behaviour of openboard v1.6.1 using windows 10 and xubuntu 20.04 as well.

**Comment by letsfindaway** [comment]
I assume this is https://bugreports.qt.io/browse/QTBUG-84462. It is fixed in Qt 5.15.1, but due to another problem showing up in that version (see #479) OpenBoard currently uses Qt 5.15.0.

**Comment by maehne** [comment]
I am observing the same behaviour. In our class rooms, we are fortunate to have two screens. Typically, I use one screen to show slides and the other to do demonstrations in some tool or show additional ressources (e.g., Moodle web site, SpeakUp or some video conference tool). To avoid having to turn my head to see the content on the second screen, I attach an additional external monitor to my Laptop and set the two screens on the wall to mirror the two screens on the teacher desk. To be able to work with OpenBoard in this configuration, I have to set it to single screen mode and additionally configure the screen with OpenBoard to be the primary screen. However, this is inconvenient when demonstrating some application on the other screen. E.g., if that application opens a new window, this frequently happens then on the wrong screen - the primary screen showing OpenBoard. It would be nice if this misbehaviour could be fixed.

**Comment by letsfindaway** [comment]
> I am observing the same behaviour. In our class rooms, we are fortunate to have two screens. Typically, I use one screen to show slides and the other to do demonstrations in some tool or show additional ressources (e.g., Moodle web site, SpeakUp or some video conference tool). To avoid having to turn my head to see the content on the second screen, I attach an additional external monitor to my Laptop and set the two screens on the wall to mirror the two screens on the teacher desk. To be able to work with OpenBoard in this configuration, I have to set it to single screen mode and additionally configure the screen with OpenBoard to be the primary screen. However, this is inconvenient when demonstrating some application on the other screen. E.g., if that application opens a new window, this frequently happens then on the wrong screen - the primary screen showing OpenBoard. It would be nice if this misbehaviour could be fixed.

I think your problem is different than the original one and is **not** related to the Qt bug referenced above. The original problem is just about a menu of OpenBoard being opened on the wrong screen. Your problem is that other applications are starting on the "wrong" screen, i.e. the same where OpenBoard's control screen is located. For your problem, I just can give you some hints:

- You can configure OpenBoard to use the secondary monitor in single-monitor mode by checking the "switch control and display screen" checkbox while being in dual-monitor mode and then enabling the single-monitor mode. I think this is a good workaround and avoids having to configure the primary monitor.
- The upcoming 1.7 version will make monitor configurations even more flexible.
- Depending on your operating system and desktop environment you might be able to configure rules for the other applications on which monitor they should open.

**Comment by maehne** [comment]
@letsfindaway: Thanks for your reply and hints how to address the issue! Actually, my described use case - including the fact that newly started applications tend to start up on the primary screen - was just to illustrate, why it is a frustrating experience to use OpenBoard in single screen mode on the secondary screen, because its menus open on the wrong screen.

Your suggested workaround unfortunately *does not fix the issue* of OpenBoard menus appearing always on the primary screen (at least on the current OpenBoard 1.6.2 on Windows 11). However, OpenBoard will start after the suggested configuration on the secondary screen in single screen mode. Interestingly, the configuration windows opens on the secondary screen when it got started via the menu on the primary screen.

It would be really nice if OpenBoard would better support multi-monitor setups with more than two screens and offer more flexibility when assigning its windows to screens:

- its main window with the user interface for the presenter
- its optional secondary window with the current slide covering the full screen
- its optional ternary window showing the last slide covering the full screen

The ternary window should be switchable on or off independent of the multi-screen option. IMHO, it makes no sense for OpenBoard to cover more than three screens. However, there may be a use case to allow several parallel instances of OpenBoard covering different screens to show different slide sets in parallel. E.g., in our UAS, we teach several courses in bilingual mode, i.e., in German and French during the same lesson. In that case, it would sometimes be nice to be able to show localised versions of the same set of slides in a synchronous fashion. I admit that this might be a rather rare case -- I have seen it too on several occasions during PhD defenses (English for the main audience + mother tongue for the family/friends). The general need of working with two sets of slides in parallel is more common, e.g., every time you want to solve exercises together with the students and refer to certain slides from the theory slide deck.

I am aware that certain window managers on Linux allow to define rules to assign certain applications to certain screens. However, at least in my case, the monitor setup changes so frequently that it would be hard to manage/maintain defining the rule sets and switching between them.

**Comment by maehne** [comment]
Just for the record, this issue is still present in the newly released version OpenBoard 1.6.2.

**Comment by kaamui** [comment]
should be fixed on next release
