### ISSUE TITLE
can't play mp3/mp4

### ISSUE THREAD

**Issue by novazur972** [OpenBoard-org/OpenBoard#839]
On Gentoo/Linux I compiled Openboard git master branch, and I can't open mp3/mp4:
```
Warning: "No decoder available for type 'video/quicktime, variant=(string)iso'."
Error: "Your GStreamer installation is missing a plug-in."
Warning: "No decoder available for type 'application/x-id3'."
Error: "Your GStreamer installation is missing a plug-in."
```
What could I be missing please?

**Comment by letsfindaway** [comment]
I think the error message is quite clear: you might be missing a GStreamer plugin.

- Can you play other sound files with OpenBoard?
- Can you play the problematic sound file with any other media player on your system? Which one?
- Can you play the file using `gst-play-1.0 <filename>`?
- Which `gst-plugins-*` packages do you have installed? I think you need at least `gst-plugins-base` and `gst-plugins-good`.
- Did you search for this message on the Internet, trying to find any advice?
- What did you already try and test?

**Comment by novazur972** [comment]
> I think the error message is quite clear: you might be missing a GStreamer plugin.

Yes, but I don't know anything about gstreamer. And can't find anything about its dependency in OpenBoard documentation.
 
>     * Can you play other sound files with OpenBoard?

I don't know how to play sound with it except other than adding a audio/mp3.

>     * Can you play the problematic sound file with any other media player on your system? Which one?

Of course. If not, I would have a great problem and won't be here to talk about OpenBoard and audio/video :)

>     * Can you play the file using `gst-play-1.0 <filename>`?

No. same error, of course.

>     * Which `gst-plugins-*` packages do you have installed?

I never installed anything voluntary about gstreamer.
I just see gst-plugins-base is a dependancy of a lot of packages installed (qtmultimedia for example)

> I think you need at least `gst-plugins-base` 

Already have this one.

> and `gst-plugins-good`

seems not sufficient
I tried several one by one, and finally decided to install gst-plugins-meta which called:
media-libs/gst-plugins-good-1.20.6
media-plugins/gst-plugins-lame-1.20.6
media-libs/gst-plugins-ugly-1.20.6
media-plugins/gst-plugins-faad-1.20.6
media-plugins/gst-plugins-dts-1.20.6
media-plugins/gst-plugins-resindvd-1.20.6
media-plugins/gst-plugins-libav-1.20.6
media-plugins/gst-plugins-flac-1.20.6
media-plugins/gst-plugins-mpg123-1.20.6
media-plugins/gst-plugins-pulse-1.20.6
media-plugins/gst-plugins-v4l2-1.20.6
media-plugins/gst-plugins-cdparanoia-1.20.6
media-plugins/gst-plugins-a52dec-1.20.6
media-plugins/gst-plugins-dvdread-1.20.6
media-plugins/gst-plugins-mpeg2dec-1.20.6
media-plugins/gst-plugins-x264-1.20.6

surely all not needed.

And now, gst-play plays mp3, and of course OpenBoard too.
I'll add gst-plugins-meta to the dependencies of the ebuild.
I'm surprised it wasn't in https://github.com/cloc3/OpenBoard/blob/main/x11-apps/OpenBoard/OpenBoard-1.6.4.ebuild I used to make my own ebuild.

>     * Did you search for this message on the Internet, trying to find any advice?

Of course. I never ask question before trying to solve my problem myself.
But here, I wanted to know exactly what was missing. I supposed there were somewhere I could find the information about that.
The problem is that there only documentation about ubuntu packages, and I don't care about theses packages, I use Gentoo. So I really need to know EXACTLY what is needed.

I just want to remind that I am neither an OpenBoard user, nor a developer, nor a Gentoo packager. I'm just looking to install OpenBoard for my wife (under Gentoo) so that she can use it fully, and no package exists anywhere of an OpenBoard version installable on a Gentoo. So I have to do it myself, but that doesn't make me an expert of anything ;)

>     * What did you already try and test?

Nothing. What could I try without any information? ;)
And that was my question here.

Problem solved. Thanks

**Comment by letsfindaway** [comment]
Happy that it is solved!

So for your understanding some more background on this:

- OpenBoard uses the Qt media framework to play audio and video. It just passes the file to this framework and hopes it can cope with it.
- The Qt media framework selects a proper library, depending on the platform. For Windows and MacOS it is probably different from Linux.
- The library used by Qt5 on Linux is [GStreamer](https://gstreamer.freedesktop.org/), a very popular framework for encoding and decoding multimedia files. It uses a set of plugins to provide the codecs.
- All plugins are optional. But of course, if you want to support a specific media type, you need the appropriate plugin.
- Many distributions install a reasonable default set of plugins with the base installation. Also some distributions choose not to ship codecs which might contain non-free code. 
- See also https://gstreamer.freedesktop.org/documentation/additional/splitup.html?gi-language=c for an overview.

But in the end you see: OpenBoard cannot do much about this. It is a platform question.

And: In most packaging systems (at least `deb` and `rpm`) there is not only a "Depends", but also a "Recommends" or "Suggests". If you have that also in Gentoo, then choose one of those. `gst-plugins-meta` is not a strict dependency of OpenBoard. It is not absolutely necessary to run OpenBoard. It might be comfortable to just pull all the plugins in, but it is not a requirement and therefore no dependency.

**Comment by novazur972** [comment]
I'm sorry but I don't think this is correct, given that I have been using Gentoo for 22 years, and I have NO sound problems with any of my applications capable of streaming audio, whether mpv , firefox, chrome, vlc, transcode, simplescreenrecorder, ffmpeg etc etc... including Plasma/Kde and all its resulting applications kdenlive etc...
It is clearly OpenBoard which chooses to use gstreamer without taking into account my choices for my system. It is therefore an OpenBoard problem, and not a platform problem, otherwise, I would have had this need to gstream elsewhere than in OpenBoard.

**Comment by celfred** [comment]
Hello,
I follow up on video codec issue and I do agree wih @novazur972 about the issue depending on OpenBoard.
I have Linux Mint with all I can find about Gstreamer installed for that purpose (no more videos were working since last update 1.7.1rc240202) and the problem is not solved… All my videos work (and used to work) perfectly with all other softwares on my system.

I have tried to convert a video to AVI (from MP4) with video/x-msvideo codec. Although my video went from 45Mo to 157Mo (!) it works fine in OpenBoard (but I wouldn't like to convert all my videos for that purpose).

I have read such things as codec priority in Qt. Could it be a hint ? I have no idea… (https://forums.linuxmint.com/viewtopic.php?t=391549)

I hope a durable solution may be found soon…

Thanks !
